[package]
name = "appbase-macros"
version = "0.1.0"
authors = ["Jeeyong Um <conr2d@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.28"
quote = "1.0.9"
syn = "1.0.74"
